# Generated by Django 4.1.3 on 2022-11-17 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(blank=True, default='KunXXXX', max_length=20, null=True)),
                ('reg_no', models.CharField(blank=True, default='20XXX00X', max_length=20, null=True)),
                ('address', models.CharField(blank=True, default='Nanded', max_length=20, null=True)),
                ('taluka', models.CharField(blank=True, default='Nanded', max_length=20, null=True)),
                ('district', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(upload_to='uploads')),
                ('pincode', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=20, null=True)),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('semester', models.CharField(blank=True, max_length=20, null=True)),
                ('year', models.DateField()),
                ('remain', models.IntegerField(blank=True, null=True)),
                ('reg_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subject', models.CharField(blank=True, max_length=20, null=True)),
                ('feedback_message', models.CharField(blank=True, max_length=200, null=True)),
                ('reg_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subject', models.CharField(blank=True, max_length=20, null=True)),
                ('feedback_message', models.CharField(blank=True, max_length=200, null=True)),
                ('reg_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(blank=True, max_length=20, null=True)),
                ('class_room', models.CharField(blank=True, max_length=20, null=True)),
                ('branch', models.CharField(blank=True, max_length=20, null=True)),
                ('year', models.DateField()),
                ('doadmission', models.DateField()),
                ('semester', models.CharField(blank=True, max_length=20, null=True)),
                ('reg_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
    ]
