# Generated by Django 4.1.3 on 2022-11-17 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='remain',
        ),
        migrations.DeleteModel(
            name='Feedback_return',
        ),
    ]
